const common = {
	'1': true,
	'2': false,
	'-1': null,
	'-2': null,
};

export const COMMON_CONV = common;

const hgh_deg = {
	// '11': "Doctor's degree - research/scholarship and professional practice",
	// '12': "Doctor's degree - research/scholarship",
	// '13': "Doctor's degree -  professional practice",
	// '14': "Doctor's degree - other",
	'11': 'Doctoral degree',
	'12': 'Doctoral degree',
	'13': 'Doctoral degree',
	'14': 'Doctoral degree',
	'20': "Master's degree",
	'30': "Bachelor's degree",
	'40': "Associate's degree",
	'0': false,
	'-3': null,
};

const crn_basic = {
	'1': "Associate's Colleges: High Transfer-High Traditional",
	'2': "Associate's Colleges: High Transfer-Mixed Traditional/Nontraditional",
	'3': "Associate's Colleges: High Transfer-High Nontraditional",
	'4': "Associate's Colleges: Mixed Transfer/Career & Technical-High Traditional",
	'5': "Associate's Colleges: Mixed Transfer/Career & Technical-Mixed Traditional/Nontraditional",
	'6': "Associate's Colleges: Mixed Transfer/Career & Technical-High Nontraditional",
	'7': "Associate's Colleges: High Career & Technical-High Traditional",
	'8': "Associate's Colleges: High Career & Technical-Mixed Traditional/Nontraditional",
	'9': "Associate's Colleges: High Career & Technical-High Nontraditional",
	'10': 'Special Focus Two-Year: Health Professions',
	'11': 'Special Focus Two-Year: Technical Professions',
	'12': 'Special Focus Two-Year: Arts & Design',
	'13': 'Special Focus Two-Year: Other Fields',
	'14': "Baccalaureate/Associate's Colleges: Associate's Dominant",
	'15': 'Doctoral Universities: Very High Research Activity',
	'16': 'Doctoral Universities: High Research Activity',
	'17': 'Doctoral/Professional Universities',
	'18': "Master's Colleges & Universities: Larger Programs",
	'19': "Master's Colleges & Universities: Medium Programs",
	'20': "Master's Colleges & Universities: Small Programs",
	'21': 'Baccalaureate Colleges: Arts & Sciences Focus',
	'22': 'Baccalaureate Colleges: Diverse Fields',
	'23': "Baccalaureate/Associate's Colleges: Mixed Baccalaureate/Associate's",
	'24': 'Special Focus Four-Year: Faith-Related Institutions',
	'25': 'Special Focus Four-Year: Medical Schools & Centers',
	'26': 'Special Focus Four-Year: Other Health Professions Schools',
	'27': 'Special Focus Four-Year: Research Institutions',
	'28': 'Special Focus Four-Year: Engineering and Other Technology-Related Schools',
	'29': 'Special Focus Four-Year: Business & Management Schools',
	'30': 'Special Focus Four-Year: Arts, Music & Design Schools',
	'31': 'Special Focus Four-Year: Law Schools',
	'32': 'Special Focus Four-Year: Other Special Focus Institutions',
	'33': 'Tribal Colleges',
	'0': '(Not classified)',
	'-2': 'Not applicable, not in Carnegie universe (not accredited or nondegree-granting)',
};
const crn_ugrd = {
	'1': 'Two-year, higher part-time',
	'2': 'Two-year, mixed part/full-time',
	'3': 'Two-year, medium full-time',
	'4': 'Two-year, higher full-time',
	'5': 'Four-year, higher part-time',
	'6': 'Four-year, medium full-time, inclusive, lower transfer-in',
	'7': 'Four-year, medium full-time, inclusive, higher transfer-in',
	'8': 'Four-year, medium full-time, selective, lower transfer-in',
	'9': 'Four-year, medium full-time , selective, higher transfer-in',
	'10': 'Four-year, full-time, inclusive, lower transfer-in',
	'11': 'Four-year, full-time, inclusive, higher transfer-in',
	'12': 'Four-year, full-time, selective, lower transfer-in',
	'13': 'Four-year, full-time, selective, higher transfer-in',
	'14': 'Four-year, full-time, more selective, lower transfer-in',
	'15': 'Four-year, full-time, more selective, higher transfer-in',
	'0': 'Not classified (Exclusively Graduate)',
	'-2': 'Not applicable, not in Carnegie universe (not accredited or nondegree-granting)',
};
const crn_enrl = {
	// NOTE: MORE USEFUL FOR AI OVERVIEW MORE THAN ACTUAL WEBSITE
	'1': 'Exclusively undergraduate two-year',
	'2': 'Exclusively undergraduate four-year',
	'3': 'Very high undergraduate',
	'4': 'High undergraduate',
	'5': 'Majority undergraduate',
	'6': 'Majority graduate',
	'7': 'Exclusively graduate',
	'0': '(Not classified)',
	'-2': 'Not applicable, not in Carnegie universe (not accredited or nondegree-granting)',
};
const crn_size = {
	'1': 'Two-year, very small',
	'2': 'Two-year, small',
	'3': 'Two-year, medium',
	'4': 'Two-year, large',
	'5': 'Two-year, very large',
	'6': 'Four-year, very small, primarily nonresidential',
	'7': 'Four-year, very small, primarily residential',
	'8': 'Four-year, very small, highly residential',
	'9': 'Four-year, small, primarily nonresidential',
	'10': 'Four-year, small, primarily residential',
	'11': 'Four-year, small, highly residential',
	'12': 'Four-year, medium, primarily nonresidential',
	'13': 'Four-year, medium, primarily residential',
	'14': 'Four-year, medium, highly residential',
	'15': 'Four-year, large, primarily nonresidential',
	'16': 'Four-year, large, primarily residential',
	'17': 'Four-year, large, highly residential',
	'18': 'Exclusively graduate/professional',
	'0': '(Not classified)',
	'-2': 'Not applicable, not in Carnegie universe (not accredited or nondegree-granting)',
};
const urban = {
	'11': 'City: Large',
	'12': 'City: Midsize',
	'13': 'City: Small',
	'21': 'Suburb: Large',
	'22': 'Suburb: Midsize',
	'23': 'Suburb: Small',
	'31': 'Town: Fringe',
	'32': 'Town: Distant',
	'33': 'Town: Remote',
	'41': 'Rural: Fringe',
	'42': 'Rural: Distant',
	'43': 'Rural: Remote',
	'-3': null,
};

const inst_control = {
	'1': 'Public',
	'2': 'Private for-profit',
	'3': 'Private non-profit',
	'4': 'Private non-profit',
	// '3': 'Private non-profit (no religious affiliation)',
	// '4': 'Private non-profit (religious affiliation)',
	'-1': null,
};

const relig_control = {
	'51': 'African Methodist Episcopal',
	'24': 'African Methodist Episcopal Zion Church',
	'52': 'American Baptist',
	'22': 'American Evangelical Lutheran Church',
	'53': 'American Lutheran',
	'27': 'Assemblies of God Church',
	'54': 'Baptist',
	'28': 'Brethren Church',
	'109': 'Buddhist/Buddhism',
	'34': 'Christ and Missionary Alliance Church',
	'61': 'Christian Church (Disciples of Christ)',
	'48': 'Christian Churches and Churches of Christ',
	'55': 'Christian Methodist Episcopal',
	'35': 'Christian Reformed Church',
	'58': 'Church of Brethren',
	'57': 'Church of God',
	'59': 'Church of the Nazarene',
	'74': 'Churches of Christ',
	'60': 'Cumberland Presbyterian',
	'101': 'Ecumenical Christian',
	'50': 'Episcopal Church, Reformed',
	'102': 'Evangelical Christian',
	'36': 'Evangelical Congregational Church',
	'37': 'Evangelical Covenant Church of America',
	'38': 'Evangelical Free Church of America',
	'39': 'Evangelical Lutheran Church',
	'64': 'Free Methodist',
	'41': 'Free Will Baptist Church',
	'65': 'Friends',
	'105': 'General Baptist',
	'91': 'Greek Orthodox',
	'42': 'Interdenominational',
	'40': 'International United Pentecostal Church',
	'80': 'Jewish',
	'68': 'Lutheran Church - Missouri Synod',
	'67': 'Lutheran Church in America',
	'43': 'Mennonite Brethren Church',
	'69': 'Mennonite Church',
	'87': 'Missionary Church Inc',
	'44': 'Moravian Church',
	'78': 'Multiple Protestant Denomination',
	'106': 'Muslim',
	'108': 'Non-Denominational',
	'45': 'North American Baptist',
	'100': 'Original Free Will Baptist',
	'110': 'Orthodox Christian',
	'79': 'Other Protestant',
	'47': 'Pentecostal Holiness Church',
	'107': 'Plymouth Brethren',
	'103': 'Presbyterian',
	'66': 'Presbyterian Church (USA)',
	'73': 'Protestant Episcopal',
	'77': 'Protestant, not specified',
	'49': 'Reformed Church in America',
	'81': 'Reformed Presbyterian Church',
	'30': 'Roman Catholic',
	'92': 'Russian Orthodox',
	'95': 'Seventh Day Adventist',
	'75': 'Southern Baptist',
	'94': 'The Church of Jesus Christ of Latter-day Saints',
	'97': 'The Presbyterian Church in America',
	'88': 'Undenominational',
	'93': 'Unitarian Universalist',
	'84': 'United Brethren Church',
	'76': 'United Church of Christ',
	'71': 'United Methodist',
	'104': 'Virginia Baptist General Association',
	'89': 'Wesleyan',
	'33': 'Wisconsin Evangelical Lutheran Synod',
	'99': 'Other (Not Specified)',
	'-1': null,
	'-2': null,
};

const cal_sys = {
	'1': 'Semester',
	'2': 'Quarter',
	'3': 'Trimester',
	'4': 'Four-one-four',
	'5': 'Other',
	'6': 'Differs',
	'7': 'Continuous',
	'-2': null,
};

export const INFO_CONV = {
	hgh_deg,
	hospital: common,
	med_deg: common,
	crn_basic,
	crn_enrl,
	crn_size,
	crn_ugrd,
	urban,
	mc_sys: common,
	inst_control,
	relig_control,
	cal_sys,
	ncaa_affl: common,
};

const considerations = {
	'1': 'Required',
	'5': 'Considered',
	'3': 'Not Considered',
	'-1': null,
	'-2': null,
};

const considerations_names = {
	con_hs_gpa: 'High School GPA',
	con_class_rank: 'Class Rank',
	con_hs_record: 'High School Record',
	con_prep_program: 'Completion of College-Preparatory Program',
	con_recommendations: 'Recommendations',
	con_competencies:
		'Formal Demonstration of Compentencies (portfolios, certificates, assessments)',
	con_test_scores: 'Admission Test Scores (SAT, ACT, etc.)',
	con_english_test: 'English Proficiency Test (for applicable students)',
	con_other_tests: 'Other Tests (Wonderlic, WISC-III, etc.)',
	con_work_experience: 'Work Experience',
	con_essay: 'Essays/Personal Statements',
	con_legacy: 'Legacy',
};

export const CONSIDERATIONS_CONV = {
	...considerations,
	names: considerations_names,
};

export const ADMISSIONS_CONV = {
	considerations: CONSIDERATIONS_CONV,
	ap_credit: common,
};

const instsize = {
	'1': 'Under 1,000',
	'2': '1,000 - 4,999',
	'3': '5,000 - 9,999',
	'4': '10,000 - 19,999',
	'5': '20,000 and above',
	'-1': null,
	'-2': null,
};

export const ENROLLMENT_CONV = {
	offers_ugrd: common,
	offers_grad: common,
	frsh_camp_req: common,
	online: common,
	instsize,
};

const offers_meal_plan = {
	'1': 'Yes, number of meals in the maximum meal plan offered', // TODO: Make this more similar to common
	'2': 'Yes, number of meals per week can vary',
	'3': false,
	'-1': null,
	'-2': null,
};

export const COSTS_CONV = {
	tuit_vary: common,
	offers_housing: common,
	offers_meal_plan,
};

export const SERVICES_CONV = {
	rotc: common,
	study_abroad: common,
	teacher_cert: common,
	ug_research: common,
	no_special_learning: common,
	career_counseling: common,
	employment_services: common,
	placement_services: common,
	no_student_services: common,
};
